"""empty message

Revision ID: 1857c9c37829
Revises: 46ce2f04aa31
Create Date: 2015-11-23 10:11:14.922000

"""

# revision identifiers, used by Alembic.
revision = '1857c9c37829'
down_revision = '46ce2f04aa31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comentario', 'text',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('problem', 'description',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'description',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('comentario', 'text',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    ### end Alembic commands ###
