"""empty message

Revision ID: 46ce2f04aa31
Revises: None
Create Date: 2015-11-23 10:08:42.162000

"""

# revision identifiers, used by Alembic.
revision = '46ce2f04aa31'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
