"""empty message

Revision ID: 1ad22291eb4b
Revises: e5ccc42c5b0
Create Date: 2015-11-27 15:13:10.264000

"""

# revision identifiers, used by Alembic.
revision = '1ad22291eb4b'
down_revision = 'e5ccc42c5b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'comentario', 'problem',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'comentario', 'text',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column(u'comentario', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'follower', 'problem',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'follower', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'problem', 'category',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column(u'problem', 'description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column(u'problem', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column(u'problem', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column(u'problem', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column(u'problem', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column(u'user', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column(u'problem', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'problem', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column(u'problem', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column(u'problem', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column(u'problem', 'description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column(u'problem', 'category',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column(u'follower', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'follower', 'problem',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'comentario', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'comentario', 'text',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column(u'comentario', 'problem',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('teste')
    ### end Alembic commands ###
