"""empty message

Revision ID: 1d2daf389639
Revises: None
Create Date: 2015-11-23 15:09:29.702000

"""

# revision identifiers, used by Alembic.
revision = '1d2daf389639'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
