"""empty message

Revision ID: 21d5ce7720cf
Revises: 385de136c846
Create Date: 2015-11-23 16:17:00.012000

"""

# revision identifiers, used by Alembic.
revision = '21d5ce7720cf'
down_revision = '385de136c846'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
