"""empty message

Revision ID: 385de136c846
Revises: 1d2daf389639
Create Date: 2015-11-23 15:12:28.360000

"""

# revision identifiers, used by Alembic.
revision = '385de136c846'
down_revision = '1d2daf389639'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('matricula', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['matricula'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'matricula')
    ### end Alembic commands ###
