"""empty message

Revision ID: 45b29820dcc9
Revises: 21d5ce7720cf
Create Date: 2015-11-24 12:21:21.590000

"""

# revision identifiers, used by Alembic.
revision = '45b29820dcc9'
down_revision = '21d5ce7720cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
