"""empty message

Revision ID: 511e24cd0e15
Revises: 3db8d3c612d7
Create Date: 2015-11-30 07:50:12.510000

"""

# revision identifiers, used by Alembic.
revision = '511e24cd0e15'
down_revision = '3db8d3c612d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('image', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'image')
    ### end Alembic commands ###
