"""empty message

Revision ID: e5ccc42c5b0
Revises: 45b29820dcc9
Create Date: 2015-11-24 12:22:13.610000

"""

# revision identifiers, used by Alembic.
revision = 'e5ccc42c5b0'
down_revision = '45b29820dcc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
